# Generated by Django 4.1.5 on 2023-01-11 14:48

import Manager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.CharField(max_length=15)),
                ('initialPayableAmount', models.IntegerField(default=0)),
                ('updatedPayableAmount', models.IntegerField(default=0)),
                ('paidAmount', models.IntegerField(default=0)),
                ('dueDate', models.DateTimeField(default=Manager.models.in_seven_days)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementStatus', models.CharField(blank=True, max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.invoice')),
            ],
        ),
    ]
