# Generated by Django 4.1.5 on 2023-01-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Manager', '0002_alter_invoice_paidamount_alter_invoice_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statement',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statement',
            name='debit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.appuser'),
        ),
    ]
