# Generated by Django 4.1.5 on 2023-01-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_statement_balance_statement_credit_statement_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='debit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
