# Generated by Django 4.1.5 on 2023-01-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_alter_statement_balance_alter_statement_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.invoice'),
        ),
    ]
