# Generated by Django 4.1.5 on 2023-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_alter_statement_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='totalBalance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
