# Generated by Django 4.1.5 on 2023-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_statement_totalbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='updateBalance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
