# Generated by Django 4.1.5 on 2023-01-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_statement_updatebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='totalBalance',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='updateBalance',
        ),
    ]
